version = 1

test_patterns = ["spec/**"]

exclude_patterns = [
  "**/Rakefile",
  "db/**/*",
  "spec/**/*",
  "node_modules/**/*"
]

[[analyzers]]
name = "test-coverage"
enabled = true

[[analyzers]]
name = "shell"
enabled = true

[[analyzers]]
name = "ruby"
enabled = true

[[analyzers]]
name = "javascript"
enabled = true

[[transformers]]
name = "prettier"
enabled = true

[[transformers]]
name = "standardjs"
enabled = true