version = 1

test_patterns = ["spec/**"]

exclude_patterns = [
  "**/Rakefile",
  "db/**/*",
  "bin/**/*",
  "config/initializers/**/*",
  "tmp/**/*",
  "vendor/bundle/**/*",
  "config/application.rb",
  "config/environments/**/*",
  "spec/**/*",
  "node_modules/**/*"
]

[[analyzers]]
name = "ruby"
enabled = true

[[analyzers]]
name = "javascript"
enabled = true

[[transformers]]
name = "prettier"
enabled = true

[[transformers]]
name = "standardjs"
enabled = true