previewsEnabled: true
previewsExpireAfterDays: 3

databases:
  - name: tempura-db
    region: frankfurt
    plan: starter

services:
  - type: web
    name: tempura-web
    env: ruby
    initialDeployHook: ./bin/render-preview.sh
    region: frankfurt
    plan: starter
    buildCommand: DB_MIGRATE=true ./bin/render-build.sh
    startCommand: REDIS_URL="redis://${REDIS_HOST}" bundle exec puma -C config/puma.rb
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: tempura-db
          property: connectionString
      - key: REDIS_HOST
        fromService:
          name: tempura-redis
          type: pserv
          property: hostport
      - fromGroup: app-settings
  - type: worker
    name: tempura-sidekiq
    env: ruby
    region: frankfurt
    plan: starter
    buildCommand: ./bin/render-build.sh
    startCommand: REDIS_URL="redis://${REDIS_HOST}" bundle exec sidekiq -e production
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: tempura-db
          property: connectionString
      - key: REDIS_HOST
        fromService:
          name: tempura-redis
          type: pserv
          property: hostport
      - fromGroup: app-settings
  - type: pserv
    name: tempura-redis
    env: docker
    region: frankfurt
    plan: starter
    repo: https://github.com/render-examples/redis.git
    numInstances: 1
    disk:
      name: tempura-redis-data
      mountPath: /var/lib/redis
      sizeGB: 1
