previewsEnabled: true
previewsExpireAfterDays: 3

databases:
  - name: tempura-db
    plan: free
    region: frankfurt

services:
  - type: web
    name: tempura-web
    env: ruby
    initialDeployHook: ./bin/render-preview.sh
    region: frankfurt
    plan: free
    buildCommand: DB_MIGRATE=true ./bin/render-build.sh
    startCommand: REDIS_URL="redis://${REDIS_HOST}" bundle exec puma -C config/puma.rb
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: tempura-db
          property: connectionString
      - key: REDIS_HOST
        fromService:
          name: tempura-redis
          type: pserv
          property: hostport
      - fromGroup: app-settings

  - type: worker
    name: tempura-sidekiq
    env: ruby
    region: frankfurt
    plan: free
    buildCommand: ./bin/render-build.sh
    startCommand: REDIS_URL="redis://${REDIS_HOST}" bundle exec sidekiq -e production
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: tempura-db
          property: connectionString
      - key: REDIS_HOST
        fromService:
          name: tempura-redis
          type: pserv
          property: hostport
      - fromGroup: app-settings

  - type: pserv
    name: tempura-redis
    env: docker
    region: frankfurt
    repo: https://github.com/render-examples/redis.git
    numInstances: 1
    disk:
      name: tempura-redis-data
      mountPath: /var/lib/redis
      sizeGB: 1

envVarGroups:
  - name: app-settings
    envVars:
      - key: BASIC_AUTH_ENABLED
        value: false
      - key: RAILS_MASTER_KEY
        sync: false
      - key: RAILS_LOG_TO_STDOUT
        value: true
      - key: RAILS_SERVE_STATIC_ASSETS
        value: true
      - key: SMTP_ADDRESS
        value: smtp.sendgrid.net
      - key: SMTP_DOMAIN
        sync: false
      - key: SMTP_PASSWORD
        value: password
        previewValue: password
      - key: SMTP_USERNAME
        value: username
        previewValue: username
      - key: SECRET_KEY_BASE
        generateValue: true