databases:
  - name: tempura-db
    region: frankfurt

services:
  - type: web
    name: tempura-web
    env: ruby
    region: frankfurt
    buildCommand: DB_MIGRATE=true ./bin/render-build.sh
    startCommand: REDIS_URL="redis://${REDIS_HOST}" bundle exec puma -C config/puma.rb
    envVars:
      - key: ASSET_HOST
        fromService:
          name: tempura-web
          property: host
      - key: APPLICATION_HOST
        fromService:
          name: tempura-web
          property: host
      - key: DATABASE_URL
        fromDatabase:
          name: tempura-db
          property: connectionString
      - key: REDIS_HOST
        fromService:
          name: tempura-redis
          type: pserv
          property: hostport
      - fromGroup: app-settings

  - type: worker
    name: tempura-sidekiq
    env: ruby
    region: frankfurt
    plan: starter
    buildCommand: ./bin/render-build.sh
    startCommand: REDIS_URL="redis://${REDIS_HOST}" bundle exec sidekiq -e production
    envVars:
      - key: ASSET_HOST
        fromService:
          name: tempura-web
          property: host
      - key: APPLICATION_HOST
        fromService:
          name: tempura-web
          property: host
      - key: DATABASE_URL
        fromDatabase:
          name: tempura-db
          property: connectionString
      - key: REDIS_HOST
        fromService:
          name: tempura-redis
          type: pserv
          property: hostport
      - fromGroup: app-settings

  - type: pserv
    name: tempura-redis
    env: docker
    region: frankfurt
    repo: https://github.com/render-examples/redis.git
    numInstances: 1
    disk:
      name: tempura-redis-data
      mountPath: /var/lib/redis
      sizeGB: 1

envVarGroups:
  - name: app-settings
    - key: EMAIL_RECIPIENTS
      sync: false
    - key: RAILS_MASTER_KEY
      sync: false
    - key: RAILS_LOG_TO_STDOUT
      value: true
    - key: RAILS_SERVE_STATIC_ASSETS
      value: true
    - key: SMTP_ADDRESS
      sync: false
    - key: SMTP_DOMAIN
      sync: false
    - key: SMTP_PASSWORD
      sync: false
    - key: SMTP_USERNAME
      sync: false
    - key: SECRET_KEY_BASE
      generateValue: true
